import {createContext,useContext,useEffect,useState} from 'react';
import {BrowserRouter,Routes,Route,Link,Navigate,useNavigate,useParams} from 'react-router-dom';
import {QueryClient,QueryClientProvider,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,Home,LogOut,Plus,ClipboardList,Eye,EyeOff,Star,Trash2,LoaderCircle} from 'lucide-react';
import {api} from './api';
import './styles.css';

type User={email:string;role:string;name:string};
type Notice={id:number;title:string;source_name:string;raw_text:string;created_at:string;is_favorite:boolean;extraction?:Record<string,unknown>};
type AuthState={user:User|null;loading:boolean;refresh:()=>Promise<void>;logout:()=>Promise<void>};
const AuthContext=createContext<AuthState|null>(null);
const useAuth=()=>{const value=useContext(AuthContext);if(!value)throw new Error('Auth provider is missing');return value};
function AuthProvider({children}:{children:React.ReactNode}){const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true);const refresh=async()=>{try{const response=await api.get<User>('/api/me');setUser(response.data)}catch{setUser(null)}finally{setLoading(false)}};useEffect(()=>{localStorage.removeItem('token');void refresh()},[]);const logout=async()=>{try{await api.post('/api/auth/logout')}finally{setUser(null)}};return <AuthContext.Provider value={{user,loading,refresh,logout}}>{children}</AuthContext.Provider>}
function Logo(){return <Link className="logo" aria-label="Notiq home" to="/"><svg className="logo-mark" viewBox="0 0 44 44" aria-hidden="true"><path d="M6 35V10.5c0-2.8 3.4-4.2 5.4-2.2l15 15V10.5c0-2.8 3.4-4.2 5.4-2.2l6.2 6.1v20.1c0 2.8-3.4 4.2-5.4 2.2l-15-15V35c0 2.8-3.4 4.2-5.4 2.2L7.3 37A3.1 3.1 0 0 1 6 35Z"/><path className="logo-spark" d="m22 25.3 1.8 4.9 4.9 1.8-4.9 1.8-1.8 4.9-1.8-4.9-4.9-1.8 4.9-1.8 1.8-4.9Z"/></svg><span className="logo-wordmark">Notiq</span></Link>}
function IconLink({to,label,children}:{to:string;label:string;children:React.ReactNode}){return <Link className="nav-icon" to={to} aria-label={label} title={label}>{children}</Link>}
function Nav(){const {user,loading,logout}=useAuth();const navigate=useNavigate();if(loading)return <nav className="nav"><Logo/><span className="nav-loading"><LoaderCircle size={16}/> Restoring session</span></nav>;return <nav className="nav"><Logo/><div className="nav-actions">{user?<><IconLink to="/dashboard" label="Dashboard"><Home size={19}/></IconLink><IconLink to="/upload" label="Upload notice"><Plus size={20}/></IconLink><IconLink to="/tasks" label="Tasks"><ClipboardList size={19}/></IconLink><button className="nav-icon" aria-label="Log out" title="Log out" onClick={async()=>{await logout();navigate('/')}}><LogOut size={18}/></button></>:<><Link className="text-action" to="/login">Sign in</Link><Link className="button" to="/register">Create account</Link></>}</div></nav>}
function PageTools({back}:{back:string}){const {user}=useAuth();return <div className="page-tools"><Link to={back} className="back-link"><ArrowLeft size={15}/> Back</Link><IconLink to={user?'/dashboard':'/'} label={user?'Dashboard':'Home'}><Home size={17}/></IconLink></div>}
function Landing(){const {user,loading}=useAuth();return <main className="landing"><section><span className="tag">College notices, made clear</span><h1>Never miss what<br/>matters.</h1><p>Upload a notice. NoticeLens finds actions, deadlines, documents and contacts—then keeps every answer tied to its source.</p>{!loading&&<Link className="button" to={user?'/upload':'/register'}>{user?'Upload a notice':'Create your account'}</Link>}</section><aside className="document-sheet"><span className="eyebrow">NOTICE PREVIEW</span><h2>From notice to next step</h2><div className="notice"><b>01 / Upload</b><p>PDF, photo, or pasted text.</p></div><div className="notice"><b>02 / Understand</b><p>Source-based facts and clear actions.</p></div><div className="notice"><b>03 / Act</b><p>Track what you need to do.</p></div></aside></main>}
function Auth({register=false}:{register?:boolean}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false);const {refresh,user}=useAuth();const nav=useNavigate();useEffect(()=>{if(user)nav('/dashboard',{replace:true})},[user,nav]);async function go(e:React.FormEvent){e.preventDefault();setErr('');setBusy(true);try{if(register)await api.post('/api/auth/register',{email,password});else await api.post('/api/auth/login',new URLSearchParams({username:email,password}));await refresh();nav('/dashboard',{replace:true})}catch(e:any){setErr(e.response?.data?.detail||'We could not reach NoticeLens. Please try again.')}finally{setBusy(false)}}return <main className="auth card"><PageTools back="/"/><span className="eyebrow">NOTICE LENS / STUDENT ACCESS</span><h1>{register?'A calmer way to stay informed.':'Welcome back.'}</h1><p>Private notice intelligence for your college life.</p><form onSubmit={go}><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password">Password</label><div className="password"><input id="password" type={show?'text':'password'} autoComplete={register?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={show?'Hide password':'Show password'} className="reveal" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{err&&<p role="alert" className="error">{err}</p>}<button disabled={busy}>{busy?'Checking…':register?'Create account':'Sign in'}</button></form><p>{register?'Already have an account?':'New to NoticeLens?'} <Link to={register?'/login':'/register'} className="text-link">{register?'Sign in':'Create an account'}</Link></p></main>}
function Protected({children}:{children:React.ReactNode}){const {user,loading}=useAuth();if(loading)return <main className="state">Restoring your secure session…</main>;return user?<>{children}</>:<Navigate to="/login" replace/>}
function Dashboard(){const q=useQuery({queryKey:['notices'],queryFn:()=>api.get<Notice[]>('/api/notices').then(r=>r.data)});const tasks=useQuery({queryKey:['tasks'],queryFn:()=>api.get('/api/tasks').then(r=>r.data)});return <main><div className="row space"><div><span className="eyebrow">YOUR LIBRARY</span><h1>Notices, clarified.</h1><p>Your notices, next actions, and source-backed answers.</p></div><Link className="button" to="/upload">Add a notice</Link></div><div className="grid"><section className="card"><h2>Recent notices</h2>{q.isLoading?<p>Loading your library…</p>:q.isError?<p className="error">Could not load notices. Refresh the page or sign in again.</p>:q.data?.length?q.data.map(n=><Link key={n.id} to={`/notices/${n.id}`} className="notice" style={{display:'block'}}><b>{n.title}</b><p className="muted">{n.source_name} · {new Date(n.created_at).toLocaleDateString()}</p></Link>):<p>No notices yet. Upload one or paste its text to begin.</p>}</section><aside className="card"><h2>Open tasks</h2>{tasks.data?.filter((t:any)=>!t.completed).length?tasks.data.filter((t:any)=>!t.completed).slice(0,5).map((t:any)=><p key={t.id}>□ {t.title}</p>):<p>No open actions detected.</p>}<Link to="/tasks" className="text-link">View all tasks</Link></aside></div></main>}
function Upload(){const [text,setText]=useState(''),[file,setFile]=useState<File|null>(null),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const nav=useNavigate();async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setErr('');try{let r;if(file){const f=new FormData();f.append('file',file);r=await api.post('/api/notices/upload',f)}else r=await api.post('/api/notices/text',{text});nav(`/notices/${r.data.id}`)}catch(e:any){setErr(e.response?.data?.detail||'Upload failed. Please try a supported file or paste the notice text.')}finally{setBusy(false)}}return <main className="card narrow"><PageTools back="/dashboard"/><h1>Add a notice</h1><p>We preserve the original text so you can verify every extracted detail.</p><form onSubmit={submit}><label htmlFor="file">Upload PDF, PNG, or JPG</label><input id="file" type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><p className="muted">Or paste notice text</p><textarea value={text} disabled={!!file} onChange={e=>setText(e.target.value)} placeholder="Paste the full notice here…" required={!file}/>{err&&<p role="alert" className="error">{err}</p>}<button disabled={busy}>{busy?'Processing…':'Extract notice'}</button></form></main>}
function Detail(){const {id=''}=useParams();const qc=useQueryClient();const nav=useNavigate();const q=useQuery({queryKey:['notice',id],queryFn:()=>api.get<Notice>(`/api/notices/${id}`).then(r=>r.data)});const [question,setQuestion]=useState(''),[answer,setAnswer]=useState<any>(),[deleting,setDeleting]=useState(false);if(q.isLoading)return <main className="state">Loading notice…</main>;if(!q.data)return <main className="state">Notice unavailable.</main>;const n=q.data,f=n.extraction||{},contacts=[...(Array.isArray(f.contacts)?f.contacts:[]),...(Array.isArray(f.links)?f.links:[])];async function ask(e:React.FormEvent){e.preventDefault();setAnswer((await api.post(`/api/notices/${id}/qa`,{question})).data)}async function remove(){if(!window.confirm(`Delete “${n.title}”? This cannot be undone.`))return;setDeleting(true);try{await api.delete(`/api/notices/${id}`);await qc.invalidateQueries({queryKey:['notices']});nav('/dashboard')}catch{setDeleting(false);window.alert('Could not delete this notice. Please try again.')}}return <main><PageTools back="/dashboard"/><div className="notice-hero row space"><div><span className="tag">Source: {n.source_name}</span><h1>{n.title}</h1></div><div className="row"><button className="nav-icon" aria-label="Toggle saved notice" title="Save notice" onClick={async()=>{await api.patch(`/api/notices/${id}/favorite`);qc.invalidateQueries({queryKey:['notice',id]})}}><Star size={18} fill={n.is_favorite?'currentColor':'none'}/></button><button className="nav-icon danger" aria-label="Delete notice" title="Delete notice" disabled={deleting} onClick={remove}><Trash2 size={18}/></button></div></div><div className="grid"><section className="document-sheet"><h2>What you need to do</h2>{Array.isArray(f.actions)&&f.actions.length?(f.actions as string[]).map(x=><p key={x}>□ {x}</p>):<p>Not mentioned in the notice.</p>}<h2>Deadlines</h2>{Array.isArray(f.deadlines)&&f.deadlines.length?(f.deadlines as string[]).map(x=><p key={x}>{x}</p>):<p>Not mentioned in the notice.</p>}<h2>Verify against original</h2><pre>{n.raw_text}</pre></section><aside><div className="card"><h2>Ask this notice</h2><form onSubmit={ask}><label className="sr-only" htmlFor="question">Ask a question</label><input id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What is the last date?"/><button>Ask</button></form>{answer&&<><p>{answer.answer}</p>{answer.sources.map((s:string)=><div className="source" key={s}>{s}</div>)}</>}</div><div className="card stack"><h2>Contacts & links</h2>{contacts.length?contacts.map((x:any)=><p key={x}>{x}</p>):<p>Not mentioned in the notice.</p>}</div></aside></div></main>}
function Tasks(){const q=useQuery({queryKey:['tasks'],queryFn:()=>api.get('/api/tasks').then(r=>r.data)});const qc=useQueryClient();return <main className="card narrow"><PageTools back="/dashboard"/><h1>Tasks</h1>{q.data?.length?q.data.map((t:any)=><p key={t.id}><input style={{width:'auto'}} type="checkbox" checked={t.completed} aria-label={`Mark ${t.title} complete`} onChange={async()=>{await api.patch(`/api/tasks/${t.id}?completed=${!t.completed}`);qc.invalidateQueries({queryKey:['tasks']})}}/> {t.title}</p>):<p>No tasks detected from your notices yet.</p>}</main>}
function App(){return <BrowserRouter><AuthProvider><div className="shell"><Nav/><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="/upload" element={<Protected><Upload/></Protected>}/><Route path="/notices/:id" element={<Protected><Detail/></Protected>}/><Route path="/tasks" element={<Protected><Tasks/></Protected>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></div></AuthProvider></BrowserRouter>}
const client=new QueryClient();export default ()=> <QueryClientProvider client={client}><App/></QueryClientProvider>;
